kind: CronJob
apiVersion: batch/v1

metadata: 
  name: nginx-cron

spec:
  schedule: "*/1 * * * *"
  jobTemplate:
      spec:
        template:
          metadata:
            name: pod-nginx
            labels:
              app: unique

          spec:
            containers:
            - name: job-cont
              image: busybox:latest
              command: 
              - sh
              - -c
              - >
                echo "Backup started!!";
                mkdir -p /backup &&
                mkdir -p /data &&
                cp -r /data /backup &&
                echo "Backup completed!!";
              volumeMounts:
              - name: data-volume
                mountPath: /data
              - name: backup-volume
                mountPath: /backup
            restartPolicy: OnFailure
            volumes:
            - name: data-volume
              hostPath:
                path: /data
                type: DirectoryOrCreate
            - name: backup-volume
              hostPath:
                path: /backup
                type: DirectoryOrCreate

            


