apiVersion: batch/v1
kind: Job

metadata:
  name: nginx-job

spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: unique
    spec:
      containers:
        - name: job-cont
          image: busybox:latest
          command: ["sh", "-c", "echo Hellooo guys!! && sleep 10"]   
      restartPolicy: Never
