apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: footballturnaments.football.com
spec:
  group: football.com
  scope: Namespaced
  names:
    plural: footballturnaments
    singular: footballturnament
    kind: FootballTurnament
    shortNames:
      - fbt
      - ft
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name: 
                type: string
                description: "League name"
              level:
                type: string
                description: "At which level this turnament will be organized"
              priceMoney:
                type: string
                description: "How much price will winners get"
              players:
                type: string
                description: "How many playes can play in a team"
