kind: Deployment
apiVersion: apps/v1

metadata:
  name: apache-dpl
  namespace: apache
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache-cont
        image: httpd:latest
        ports:
        - containerPort: 80
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m
