apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: apache-manager-role
  namespace: apache

rules:
- apiGroups: ["", "apps","rbac.authorization.k8s.io/v1","batch"]
  resources: ["pods","deployments","services"]
  verbs: ["get", "watch","apply","create","delete","list"]
